var uaMessages = {
	title: `${serverName} :: Безкоштовний ігровий сервер`,
	slogan: `якість, перевірена часом`,
	general: 'Головна',
	aboutServer: 'Про сервер',
	registration: 'Реєстрація',
	files: 'Файли',
	statistic: 'Статистика',
	contact: 'Контакти',
	forum: 'Форум',
	fieldsCannotEmpty: `Усі поля обов'язкові!`,
	waiting: 'Зачекайте ...',
	loginExists: 'Логін вже існує!',
	emailExists: 'Такий е-мейл вже існує',
	accountCreated: 'Аккаунт створений!',
	accountNotExists: 'Такого аккаунту не існує!',
	incorrectPassword: 'Не вірний пароль!',
	incorrerctOldPassword: 'Неправильний старий пароль!',
	invalidLogin: 'Невірний логін!',
	passwordsNotMatch: 'Паролі не співпадають!',
	passwordChanged: 'Пароль змінений',
	checkEmail: 'Перевірте пошту :)',
	incorrectEmail: 'Не коректна e-mail адреса:(...',
	mesageCanOnlyRegisteredUsers: 'Повідомлення можуть відправляти тільки зареєстровані користувачі',
	somthingWrong: 'Щось пішло не так (...',
	botsAction: 'Підозра на бот-активність (...',
	passwordChanging: 'Зміна паролю',
	forgotPassword: 'Забули пароль',
	password: 'Пароль',
	oldPassword: 'Старий пароль',
	newPassword: 'Новий пароль',
	repeatePassword: 'Повторити пароль',
	back: 'Назад',
	change: 'Змінити',
	loginName: 'Логін',
	enter: 'Увійти',
	email: 'E-mail',
	send: 'Відправити',
	messageSended: 'Повідомлення відправлено!',
	messageNotSended: 'Повідомлення не надіслано:( ...',
	invalidAnswer: 'Не вірна відповідь!',
	news: 'НОВИНИ ПРОЕКТУ',
	dataCenter: 'Датацентр',
	publishingIn: 'Опубліковано в',
	readMore: 'Детальніше ...',
	personalCabinet: 'ОСОБИСТИЙ КАБІНЕТ',
	newsCaption: 'Заголовок',
	forumMessages: 'ЧУТКИ НА ФОРУМІ',
	exit: 'Вихід',
	welcome: 'Вітаємо',
	license: 'ДАНИЙ СЕРВЕР Є ТЕСТОВИМ ВАРІАНТОМ ГРИ LINEAGEII ТА ПРИЗНАЧЕНИЙ ТІЛЬКИ ДЛЯ ОЗНАЙОМЛЕННЯ. ВСІ ПРАВА НАЛЕЖАТЬ КОМПАНІЇ NCSOFT.',
	rates: 'Рейти',
	selectIntoTop: 'Відбір в ТОП',
	selectIntoTopDescription: 'Проводиться автоматично. Необхідна умова - отримання статусу дворянина. Далі сортування відбувається від найбільшої кількості проведеного часу в грі. Відібрані в "десятку" щотижня отримуватимуть винагороду у вигляді адени. ',
	common: 'Загальна',
	commonDescription: 'Броня, зброя, біжа з "Д" - до "Діно" сетів, патрони - можливо купувати в ком`юніті шопі. Побажання, пропозиції, звіт по багам надсилайте використовуючи форму розділі "Контакти". Приємного геймплею!:)',
	ourCommunitys: 'Наші спільноти в соціальних мережах',
	contactsForm: 'Форма для зв`язку',
	fullName: 'Логін',
	emailForFeedback: 'Е-мейл (для зворотнього зв`язку) ',
	messagesText: 'Текст повідомлення',
	accounts: 'Акаунтів',
	characters: 'Персонажів',
	nobleses: 'Дворян',
	heroes: 'Героїв',
	gameMasters: 'Гейм майстрів',
	clans: 'Клани',
	allys: 'Альянсів',
	top10chars: 'Тор 10 персонажів',
	charName: 'Ігровий нік',
	charClass: 'Клас',
	charSex: 'Пол',
	clanName: 'Назва клану',
	gameTime: 'Час в грі',
	lvl: 'Рів.',
	leader: 'Лідер',
	reputation: 'Репутація',
	midLvl: 'Ср.рів',
	ally: 'Альянс',
	castles: 'Замки',
	castleName: 'Назва замку',
	owner: 'Власник',
	tax: 'Ставка податку',
	treasure: 'Казна',
	siegeDate: 'Дата облоги',
	forts: 'Форти',
	fortName: 'Назва форту'
}