var enMessages = {
	title: `${serverName} :: Free game server`,
	slogan: `time-tested quality`,
	general: 'Home',
	aboutServer: 'About server',
	registration: 'Registration',
	files: 'Files',
	statistic: 'Statistics',
	contact: 'Contacts',
	forum: 'Forum',
	fieldsCannotEmpty: 'Fields must not be empty!',
	waiting: 'Wait ...',
	loginExists: 'Login already exists!',
	accountCreated: 'Account created!',
	accountNotExists: 'Account does not exist!',
	incorrectPassword: 'Invalid password!',
	incorrerctOldPassword: 'Invalid old password!',
	invalidLogin: 'Invalid login!',
	emailExists: 'This e-mail exists',
	passwordsNotMatch: 'Passwords do not match!',
	passwordChanged: 'Password changed',
	checkEmail: 'Check mail :)',
	incorrectEmail: 'Incorrect e-mail: (...',
	mesageCanOnlyRegisteredUsers: 'Messages can only be sent by registered users',
	somthingWrong: 'Something went wrong (...',
	botsAction: 'Suspicion of bot activity (...',
	passwordChanging: 'Change password',
	forgotPassword: 'Forgot password',
	password: 'Password',
	oldPassword: 'Old password',
	newPassword: 'New password',
	repeatePassword: 'Repeat password',
	back: 'Back',
	change: 'Change',
	loginName: 'Login',
	enter: 'Login',
	email: 'E-mail',
	send: 'Send',
	messageSended: 'Message sent!',
	messageNotSended: 'Email not sent :( ...',
	invalidAnswer: 'Invalid answer!',
	news: 'PROJECT NEWS',
	dataCenter: 'Datacenter',
	publishingIn: 'Posted in',
	readMore: 'Read more ...',
	personalCabinet: 'PERSONAL OFFICE',
	newsCaption: 'Headline',
	forumMessages: 'HEARINGS ON THE FORUM',
	exit: 'Exit',
	welcome: 'Welcome',
	rates: 'Rates',
	license: 'THIS SERVER IS A TEST OPTION OF THE LINEAGE II GAME AND IS DESIGNED ONLY TO ACQUAINT PLAYERS. ALL RIGHTS OWNED BY NCSOFT. ',
	selectIntoTop: 'Selection in TOP',
	selectIntoTopDescription: 'Held automatically. A necessary condition is to obtain the status of a nobleman. The following sorting occurs from the greatest amount of time spent in the game. Selected in the top ten will receive a weekly reward in the form of Adena. ',
	common: 'General',
	commonDescription: 'Armor, weapons, bijou from "D" - to "Dino" sets, ammunition - it is possible to buy in the community store. Send wishes, suggestions, bug reports using the form to the "Contacts" section. Enjoy the gameplay! :)',
	ourCommunitys: 'Our communities in social networks',
	contactsForm: 'Contact form',
	fullName: 'Login',
	emailForFeedback: 'Email (for feedback)',
	messagesText: 'Message text',
	accounts: 'Accounts',
	characters: 'Characters',
	nobleses: 'Nobles',
	heroes: 'Heroes',
	gameMasters: 'Game Masters',
	clans: 'Clans',
	allys: 'Alliances',
	top10chars: 'Top 10 characters',
	charName: 'Game nickname',
	charClass: 'Class',
	charSex: 'Gender',
	clanName: 'Clan name',
	gameTime: 'Time in the game',
	lvl: 'Lv.',
	leader: 'Leader',
	reputation: 'Reputation',
	midLvl: 'Wed.ur',
	ally: 'Alliance',
	castles: 'Castles',
	castleName: 'Castle name',
	owner: 'Owner',
	tax: 'tax rate',
	treasure: 'Treasury',
	siegeDate: 'Siege Date',
	forts: 'Forts',
	fortName: 'Fort name'
}